name: Crate App
on:
  pull_request:
    branches: [ 'master' ]
  push:
    branches: [ 'master' ]
  workflow_dispatch:
jobs:
  
  create_ec2:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Deploy infrastructure with Terraform
        run: |
          terraform init
          terraform destroy -auto-approve
          terraform plan
          terraform apply -auto-approve
          
      - name: Retrieve EC2 Public IP
        id: get_ip
        run: |
          echo "::set-output name=ip::$(terraform output -raw ec2_public_ip)"

      - name: Wait for EC2 instance to initialize
        run: sleep 60

      
      

  connect_ec2:
    needs: [create_ec2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: change permitions to ssh key
       # run: sudo chmod 400 docker-server.key

      - name: Copy project files to EC2
        run: |
          sudo chmod 400 nginx-server.key
          ls -l
          sudo scp -o StrictHostKeyChecking=no -i docker-server.key -r ./ ec2-user@ec2-${{ steps.get_ip.outputs.ip }}.compute-1.amazonaws.com:/

      - name: connect ec2
        run: |
          sudo chmod 400 docker-server.key
          echo "EC2_PUBLIC_IP_HYPHEN=${{ env.EC2_PUBLIC_IP_HYPHEN }}"
          sudo ssh -o StrictHostKeyChecking=no -i "docker-server.key" ec2-user@${{ steps.get_ip.outputs.ip }} << EOF

      - name: configure self hosted
        run: |
          mkdir actions-runner 
          cd actions-runner
          curl -o actions-runner-linux-x64-2.321.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-x64-2.321.0.tar.gz
          tar xzf ./actions-runner-linux-x64-2.321.0.tar.gz
          ./config.sh --url https://github.com/TDVCool123/crate --token AQ634URN4OPOPFAJVU5SKWDHMVKG6
          ./run.sh
